[site]
secret = "zJ8aXM5TcXaWM2p3BNWBNlfn7oZ5kYlm"
server_name = "127.0.0.1"

[database]
host = "127.0.0.1"
port = 3306
username = "homebudget"
password = "homebudget"
name = "homebudget"

[redis]
host = "localhost"
port = 6379
database = 0